### ISSUE TITLE
CFW 3.65 Connection refused

### ISSUE THREAD

**Issue by wetor** [Cpasjuste/psp2shell#22]

**Comment by gnuton** [comment]
Got the same!
psp2loader cannot load any of the k or m modules.
the k module fails with "could not load psp2shell_k: 0x80010002".
Same message for m.

**Comment by gnuton** [comment]
NIDs maybe outdated for 3.65/3.67 for this reason it doesn't work.
An alternative to psp2shell can be found here: https://github.com/devnoname120/vitacompanion/
