### ISSUE TITLE
reload failed: can't umount app0

### ISSUE THREAD

**Issue by devnoname120** [Cpasjuste/psp2shell#9]
When performing a reload, I have the following error:
```
could not umount device: app0: (err=-2147418096)
```
This error corresponds to: `C1-2752-6, 0x80010010, SCE_ERROR_ERRNO_EBUSY`

**Comment by devnoname120** [comment]
Temporary workaround: use https://github.com/Cpasjuste/PSP2SHELL/pull/11 and add `sceAppMgrUmount("app0:");` right at the start of the app.

Warning: doing this will make the app crash if it uses the filesystem after the Vita is woken back from standby.

**Comment by Cpasjuste** [comment]
Fixed in 477cfa119d1cd97ff1de8a8804eb0a79f7a1af20 , thanks devnoname120
